# server-241.rootcode.com.bo
server {
    listen 80;
    listen 443 ssl;
    server_name server-241.rootcode.com.bo;

    ssl_certificate /etc/nginx/ssl/rootcode.com.bo-crt;
    ssl_certificate_key /etc/nginx/ssl/rootcode.com.bo-key;

    charset utf-8;
    client_max_body_size 50M;

    access_log /var/log/nginx/delivery_core_access.log;
    error_log /var/log/nginx/delivery_core_error.log;

    location / {
        proxy_pass http://192.168.100.241:80;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host api.localhost;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 5s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;
    }

    error_page 502 503 504 =200 /error_web_server.html;
    location = /error_web_server.html {
        root /var/www/html/errors;
        internal;
    }
}

# server-242.rootcode.com.bo
server {
    listen 80;
    listen 443 ssl;
    server_name server-242.rootcode.com.bo;

    ssl_certificate /etc/nginx/ssl/rootcode.com.bo-crt;
    ssl_certificate_key /etc/nginx/ssl/rootcode.com.bo-key;

    charset utf-8;
    client_max_body_size 50M;

    access_log /var/log/nginx/delivery_tracking_access.log;
    error_log /var/log/nginx/delivery_tracking_error.log;

    location / {
        proxy_pass http://192.168.100.242:80;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host tracking.localhost;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 5s;
        proxy_send_timeout 60s;
        proxy_read_timeout 3600s;
    }
    error_page 502 503 504 =200 /error_web_server.html;
    location = /error_web_server.html {
        root /var/www/html/errors;
        internal;
    }
}
