apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress
  namespace: delivery-platform
spec:
  ingressClassName: traefik
  rules:
    - host: api.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hono-core-service
                port:
                  number: 3000
    - host: tracking.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-tracking-service
                port:
                  number: 8080