apiVersion: v1
kind: Service
metadata:
  name: hono-core-service
  namespace: delivery-platform
spec:
  selector:
    app: hono-core-real
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: go-tracking-service
  namespace: delivery-platform
spec:
  selector:
    app: go-tracking-real
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP